# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'yumatakei' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yumatakei
  pod 'OAuthSwift', '~> 1.2.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  target 'yumatakeiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yumatakeiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
