# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackathonApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SwiftGen'
  pod 'ReSwift'
  pod 'Cartography', '3.0.2'
  # Pods for HackathonApp

  target 'HackathonAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackathonAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
