export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const ADD_PLAYLIST = 'ADD_PLAYLIST';

export const GET_PLAYLIST_ITEMS = 'GET_PLAYLIST_ITEMS';
export const ADD_PLAYLIST_ITEM = 'ADD_PLAYLIST_ITEM';
