# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hackathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for Hackathon

  target 'HackathonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackathonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
