# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hackathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '4.6.0'
  pod 'RxSwift', '4.1.1'
  pod 'RxCocoa', '4.1.1'
  pod 'Kingfisher', '4.6.1'
  # Pods for Hackathon

  target 'HackathonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackathonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
